apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      #prometheus.io/port:   '8080'
      prometheus.io/port:   '9090'
  
spec:
  externalTrafficPolicy: Local
  selector: 
    app: prometheus-server
  type: LoadBalancer 
  ports:
    - port: 9090
      targetPort: 9090 
#      nodePort: 30000